### ISSUE TITLE
Different measurements from Arduino and ESP32

### ISSUE THREAD

**Issue by tamerh** [Sensirion/arduino-i2c-sdp#4]
Hi, I am testing the SDP811-500Pa sensor with the example code and I am seeing different readings from Arduino and ESP32. What could be the reasons? I am getting reaction(spike in pressure) from both Arduino and ESP32 when I apply some pressure.

Also temperature seems different than my digital room thermometer which shows ~1.5-2°C lower?  

Thanks for the help. 

**ESP32 measurements**
```
DifferentialPressure[Pa]:-0.03  Temperature[Â°C]:27.58
DifferentialPressure[Pa]:-0.03  Temperature[Â°C]:27.58
DifferentialPressure[Pa]:-0.02  Temperature[Â°C]:27.59
DifferentialPressure[Pa]:-0.05  Temperature[Â°C]:27.59

```

**Arduino mega 2560 measurements**
```
DifferentialPressure[Pa]:0.65   Temperature[Â°C]:27.89
DifferentialPressure[Pa]:0.63   Temperature[Â°C]:27.88
DifferentialPressure[Pa]:0.65   Temperature[Â°C]:27.88
DifferentialPressure[Pa]:0.65   Temperature[Â°C]:27.88
```

**Comment by LeonieFierz** [comment]
Hi @tamerh 

Do you have a pressure source connected or both inlets closed when doing the comparison? If the sensor is not connected it is usual that instead of 0 Pa you get a random value around 0.

For the temperature, the datasheet states:
"The measured temperature is the temperature of the bulk silicon in the sensor. This temperature value is not only depending on the gas temperature, but also on the sensor’s surroundings......" so you can not expect that it matches the surrounding temperature.
